title: "Taehoon Lee blog"
author: "Taehoon Lee"
description: "engineering and thoughts"
permalink: /:year/:month/:day/:title/
lang: "en"

show_footer: true           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true           # keep the footer dark

number_of_recent_posts: 10
number_of_category_posts: 10

comments:                    # embed disqus or isso comments
  disqus: "taehoonlee"

plugins:
 - jekyll-feed
 - jekyll-default-layout

jekyll-archives:
  enabled: all
  layouts:
    year: archive/year
  permalinks:
    year: '/:year/'
